INSERT INTO project_roles (
    tenant_id,
    name,
    description,
    is_system,
    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES
    (0, 'Administrators', 'System project role for project administrators and elevated project governance.', TRUE, NOW(), 0, NOW(), 0),
    (0, 'Developers', 'System project role for users who actively work on development issues.', TRUE, NOW(), 0, NOW(), 0),
    (0, 'Users', 'System project role for general project participants with standard collaboration access.', TRUE, NOW(), 0, NOW(), 0);

INSERT INTO permission_definitions (
    tenant_id,
    permission_key,
    name,
    description,
    category,
    is_system,
    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES
    (0, 'ADMINISTER_PROJECTS', 'Administer Projects', 'Administer project settings, project role membership, components, versions, and project details.', 'ADMINISTRATION', TRUE, NOW(), 0, NOW(), 0),
    (0, 'EDIT_WORKFLOWS', 'Edit Workflows', 'Edit project-scoped workflows under guardrails for company-managed projects.', 'ADMINISTRATION', TRUE, NOW(), 0, NOW(), 0),
    (0, 'MANAGE_WORK_ITEM_LAYOUTS', 'Manage Work Item Layouts', 'Manage project-scoped work item layout and screen arrangements under guardrails.', 'ADMINISTRATION', TRUE, NOW(), 0, NOW(), 0),
    (0, 'BROWSE_PROJECTS', 'Browse Projects', 'Browse projects, search work items, and view work items subject to issue security.', 'PROJECT', TRUE, NOW(), 0, NOW(), 0),
    (0, 'MANAGE_SPRINTS', 'Manage Sprints', 'Create, start, complete, reorder, and configure sprints.', 'PROJECT', TRUE, NOW(), 0, NOW(), 0),
    (0, 'MANAGE_VERSIONS', 'Manage Versions', 'Create, release, archive, edit, merge, and delete project versions.', 'PROJECT', TRUE, NOW(), 0, NOW(), 0),
    (0, 'VIEW_DEVELOPMENT_TOOLS', 'View Development Tools', 'View development information linked to work items.', 'PROJECT', TRUE, NOW(), 0, NOW(), 0),
    (0, 'VIEW_READ_ONLY_WORKFLOW', 'View Read-only Workflow', 'View project and work item workflows in read-only mode.', 'PROJECT', TRUE, NOW(), 0, NOW(), 0),
    (0, 'VIEW_AGGREGATED_DATA', 'View Aggregated Data', 'View aggregated backlog, board, and deployment insights for the project.', 'PROJECT', TRUE, NOW(), 0, NOW(), 0),
    (0, 'ARCHIVE_ISSUES', 'Archive Issues', 'Archive work items instead of deleting them permanently.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'RESTORE_ARCHIVED_ISSUES', 'Restore Archived Issues', 'Restore archived work items back into active project data.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'ASSIGN_ISSUES', 'Assign Issues', 'Change the assignee on work items.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'ASSIGNABLE_USER', 'Assignable User', 'Allow a user to be selected as an assignee on work items.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'CLOSE_ISSUES', 'Close Issues', 'Close work items when workflow and resolution conditions are satisfied.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'CREATE_ISSUES', 'Create Issues', 'Create work items and subtasks within the project.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'DELETE_ISSUES', 'Delete Issues', 'Delete work items and bundled issue data.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'EDIT_ISSUES', 'Edit Issues', 'Edit work item fields subject to field-level permission rules.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'LINK_ISSUES', 'Link Issues', 'Create and delete links between work items.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'MODIFY_REPORTER', 'Modify Reporter', 'Set or update reporter on behalf of another user.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'MOVE_ISSUES', 'Move Issues', 'Move work items across projects or issue types.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'RESOLVE_ISSUES', 'Resolve Issues', 'Set or clear resolution in conjunction with workflow transitions.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'SCHEDULE_ISSUES', 'Schedule Issues', 'Edit due date and ranking or scheduling-related fields.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'SET_ISSUE_SECURITY', 'Set Issue Security', 'Set or change issue security level on work items.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'TRANSITION_ISSUES', 'Transition Issues', 'Execute workflow transitions on work items.', 'ISSUE', TRUE, NOW(), 0, NOW(), 0),
    (0, 'MANAGE_WATCHERS', 'Manage Watchers', 'Add and remove watchers on work items.', 'VOTERS_WATCHERS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'VIEW_VOTERS_AND_WATCHERS', 'View Voters and Watchers', 'View watcher and voter lists on work items.', 'VOTERS_WATCHERS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'ADD_COMMENTS', 'Add Comments', 'Add comments or internal notes to work items.', 'COMMENTS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'DELETE_ALL_COMMENTS', 'Delete All Comments', 'Delete any comment from a work item.', 'COMMENTS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'DELETE_OWN_COMMENTS', 'Delete Own Comments', 'Delete comments authored by the current user.', 'COMMENTS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'EDIT_ALL_COMMENTS', 'Edit All Comments', 'Edit any comment on a work item.', 'COMMENTS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'EDIT_OWN_COMMENTS', 'Edit Own Comments', 'Edit comments authored by the current user.', 'COMMENTS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'CREATE_ATTACHMENTS', 'Create Attachments', 'Upload attachments to work items when attachments are enabled.', 'ATTACHMENTS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'DELETE_ALL_ATTACHMENTS', 'Delete All Attachments', 'Delete any attachment from a work item.', 'ATTACHMENTS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'DELETE_OWN_ATTACHMENTS', 'Delete Own Attachments', 'Delete attachments uploaded by the current user.', 'ATTACHMENTS', TRUE, NOW(), 0, NOW(), 0),
    (0, 'WORK_ON_ISSUES', 'Work On Issues', 'Log work on work items and create worklogs.', 'TIME_TRACKING', TRUE, NOW(), 0, NOW(), 0),
    (0, 'DELETE_ALL_WORKLOGS', 'Delete All Worklogs', 'Delete any worklog entry.', 'TIME_TRACKING', TRUE, NOW(), 0, NOW(), 0),
    (0, 'DELETE_OWN_WORKLOGS', 'Delete Own Worklogs', 'Delete worklog entries authored by the current user.', 'TIME_TRACKING', TRUE, NOW(), 0, NOW(), 0),
    (0, 'EDIT_ALL_WORKLOGS', 'Edit All Worklogs', 'Edit any worklog entry.', 'TIME_TRACKING', TRUE, NOW(), 0, NOW(), 0),
    (0, 'EDIT_OWN_WORKLOGS', 'Edit Own Worklogs', 'Edit worklog entries authored by the current user.', 'TIME_TRACKING', TRUE, NOW(), 0, NOW(), 0);

INSERT INTO permission_schemes (
    id,
    tenant_id,
    name,
    description,
    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES (
    820,
    0,
    'Default Software Permission Scheme',
    'System-seeded Jira-aligned default software permission scheme for company-managed software projects.',
    NOW(),
    0,
    NOW(),
    0
);

INSERT INTO permission_scheme_entries (
    tenant_id,
    scheme_id,
    permission_key,
    grantee_type,
    grantee_ref,
    custom_field_id,
    created_at,
    created_by,
    updated_at,
    updated_by
)
SELECT
    0,
    820,
    seed.permission_key,
    seed.grantee_type,
    seed.grantee_ref,
    seed.custom_field_id,
    NOW(),
    0,
    NOW(),
    0
FROM (
    VALUES
        ('ADMINISTER_PROJECTS', 'PROJECT_LEAD', CAST(NULL AS VARCHAR(255)), CAST(NULL AS BIGINT)),
        ('ADMINISTER_PROJECTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('EDIT_WORKFLOWS', 'PROJECT_LEAD', NULL, NULL),
        ('EDIT_WORKFLOWS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('MANAGE_WORK_ITEM_LAYOUTS', 'PROJECT_LEAD', NULL, NULL),
        ('MANAGE_WORK_ITEM_LAYOUTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('BROWSE_PROJECTS', 'PROJECT_LEAD', NULL, NULL),
        ('BROWSE_PROJECTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('BROWSE_PROJECTS', 'PROJECT_ROLE', 'Developers', NULL),
        ('BROWSE_PROJECTS', 'PROJECT_ROLE', 'Users', NULL),
        ('MANAGE_SPRINTS', 'PROJECT_LEAD', NULL, NULL),
        ('MANAGE_SPRINTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('MANAGE_SPRINTS', 'PROJECT_ROLE', 'Developers', NULL),
        ('MANAGE_VERSIONS', 'PROJECT_LEAD', NULL, NULL),
        ('MANAGE_VERSIONS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('MANAGE_VERSIONS', 'PROJECT_ROLE', 'Developers', NULL),
        ('VIEW_DEVELOPMENT_TOOLS', 'PROJECT_LEAD', NULL, NULL),
        ('VIEW_DEVELOPMENT_TOOLS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('VIEW_DEVELOPMENT_TOOLS', 'PROJECT_ROLE', 'Developers', NULL),
        ('VIEW_DEVELOPMENT_TOOLS', 'PROJECT_ROLE', 'Users', NULL),
        ('VIEW_READ_ONLY_WORKFLOW', 'PROJECT_LEAD', NULL, NULL),
        ('VIEW_READ_ONLY_WORKFLOW', 'PROJECT_ROLE', 'Administrators', NULL),
        ('VIEW_READ_ONLY_WORKFLOW', 'PROJECT_ROLE', 'Developers', NULL),
        ('VIEW_READ_ONLY_WORKFLOW', 'PROJECT_ROLE', 'Users', NULL),
        ('VIEW_AGGREGATED_DATA', 'PROJECT_LEAD', NULL, NULL),
        ('VIEW_AGGREGATED_DATA', 'PROJECT_ROLE', 'Administrators', NULL),
        ('VIEW_AGGREGATED_DATA', 'PROJECT_ROLE', 'Developers', NULL),
        ('VIEW_AGGREGATED_DATA', 'PROJECT_ROLE', 'Users', NULL),
        ('ARCHIVE_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('ARCHIVE_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('RESTORE_ARCHIVED_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('RESTORE_ARCHIVED_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('ASSIGN_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('ASSIGN_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('ASSIGN_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('ASSIGNABLE_USER', 'PROJECT_LEAD', NULL, NULL),
        ('ASSIGNABLE_USER', 'PROJECT_ROLE', 'Administrators', NULL),
        ('ASSIGNABLE_USER', 'PROJECT_ROLE', 'Developers', NULL),
        ('ASSIGNABLE_USER', 'PROJECT_ROLE', 'Users', NULL),
        ('CLOSE_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('CLOSE_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('CLOSE_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('CREATE_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('CREATE_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('CREATE_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('CREATE_ISSUES', 'PROJECT_ROLE', 'Users', NULL),
        ('DELETE_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('DELETE_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('EDIT_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('EDIT_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('EDIT_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('LINK_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('LINK_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('LINK_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('LINK_ISSUES', 'PROJECT_ROLE', 'Users', NULL),
        ('MODIFY_REPORTER', 'PROJECT_LEAD', NULL, NULL),
        ('MODIFY_REPORTER', 'PROJECT_ROLE', 'Administrators', NULL),
        ('MOVE_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('MOVE_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('RESOLVE_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('RESOLVE_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('RESOLVE_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('SCHEDULE_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('SCHEDULE_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('SCHEDULE_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('SET_ISSUE_SECURITY', 'PROJECT_LEAD', NULL, NULL),
        ('SET_ISSUE_SECURITY', 'PROJECT_ROLE', 'Administrators', NULL),
        ('TRANSITION_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('TRANSITION_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('TRANSITION_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('MANAGE_WATCHERS', 'PROJECT_LEAD', NULL, NULL),
        ('MANAGE_WATCHERS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('MANAGE_WATCHERS', 'PROJECT_ROLE', 'Developers', NULL),
        ('MANAGE_WATCHERS', 'PROJECT_ROLE', 'Users', NULL),
        ('VIEW_VOTERS_AND_WATCHERS', 'PROJECT_LEAD', NULL, NULL),
        ('VIEW_VOTERS_AND_WATCHERS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('VIEW_VOTERS_AND_WATCHERS', 'PROJECT_ROLE', 'Developers', NULL),
        ('VIEW_VOTERS_AND_WATCHERS', 'PROJECT_ROLE', 'Users', NULL),
        ('ADD_COMMENTS', 'PROJECT_LEAD', NULL, NULL),
        ('ADD_COMMENTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('ADD_COMMENTS', 'PROJECT_ROLE', 'Developers', NULL),
        ('ADD_COMMENTS', 'PROJECT_ROLE', 'Users', NULL),
        ('DELETE_ALL_COMMENTS', 'PROJECT_LEAD', NULL, NULL),
        ('DELETE_ALL_COMMENTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('DELETE_OWN_COMMENTS', 'PROJECT_LEAD', NULL, NULL),
        ('DELETE_OWN_COMMENTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('DELETE_OWN_COMMENTS', 'PROJECT_ROLE', 'Developers', NULL),
        ('DELETE_OWN_COMMENTS', 'PROJECT_ROLE', 'Users', NULL),
        ('EDIT_ALL_COMMENTS', 'PROJECT_LEAD', NULL, NULL),
        ('EDIT_ALL_COMMENTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('EDIT_OWN_COMMENTS', 'PROJECT_LEAD', NULL, NULL),
        ('EDIT_OWN_COMMENTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('EDIT_OWN_COMMENTS', 'PROJECT_ROLE', 'Developers', NULL),
        ('EDIT_OWN_COMMENTS', 'PROJECT_ROLE', 'Users', NULL),
        ('CREATE_ATTACHMENTS', 'PROJECT_LEAD', NULL, NULL),
        ('CREATE_ATTACHMENTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('CREATE_ATTACHMENTS', 'PROJECT_ROLE', 'Developers', NULL),
        ('CREATE_ATTACHMENTS', 'PROJECT_ROLE', 'Users', NULL),
        ('DELETE_ALL_ATTACHMENTS', 'PROJECT_LEAD', NULL, NULL),
        ('DELETE_ALL_ATTACHMENTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('DELETE_OWN_ATTACHMENTS', 'PROJECT_LEAD', NULL, NULL),
        ('DELETE_OWN_ATTACHMENTS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('DELETE_OWN_ATTACHMENTS', 'PROJECT_ROLE', 'Developers', NULL),
        ('DELETE_OWN_ATTACHMENTS', 'PROJECT_ROLE', 'Users', NULL),
        ('WORK_ON_ISSUES', 'PROJECT_LEAD', NULL, NULL),
        ('WORK_ON_ISSUES', 'PROJECT_ROLE', 'Administrators', NULL),
        ('WORK_ON_ISSUES', 'PROJECT_ROLE', 'Developers', NULL),
        ('WORK_ON_ISSUES', 'PROJECT_ROLE', 'Users', NULL),
        ('DELETE_ALL_WORKLOGS', 'PROJECT_LEAD', NULL, NULL),
        ('DELETE_ALL_WORKLOGS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('DELETE_OWN_WORKLOGS', 'PROJECT_LEAD', NULL, NULL),
        ('DELETE_OWN_WORKLOGS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('DELETE_OWN_WORKLOGS', 'PROJECT_ROLE', 'Developers', NULL),
        ('DELETE_OWN_WORKLOGS', 'PROJECT_ROLE', 'Users', NULL),
        ('EDIT_ALL_WORKLOGS', 'PROJECT_LEAD', NULL, NULL),
        ('EDIT_ALL_WORKLOGS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('EDIT_OWN_WORKLOGS', 'PROJECT_LEAD', NULL, NULL),
        ('EDIT_OWN_WORKLOGS', 'PROJECT_ROLE', 'Administrators', NULL),
        ('EDIT_OWN_WORKLOGS', 'PROJECT_ROLE', 'Developers', NULL),
        ('EDIT_OWN_WORKLOGS', 'PROJECT_ROLE', 'Users', NULL)
) AS seed(permission_key, grantee_type, grantee_ref, custom_field_id);

SELECT setval(
    pg_get_serial_sequence('permission_schemes', 'id'),
    (SELECT MAX(id) FROM permission_schemes)
);
