keycloak.url=${KEYCLOAK_URL}
keycloak.jwk-set-uri=${KEYCLOAK_URL}/realms/serp/protocol/openid-connect/certs
keycloak.expected-issuer=${KEYCLOAK_URL}/realms/serp
keycloak.expected-audience=serp-ttcrs
keycloak.realm=serp
keycloak.client-id=serp-ttcrs
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

keycloak.constant.realm-access=realm_access
keycloak.constant.resource-access=resource_access
keycloak.constant.roles-attribute=roles
