spring:
  application:
    app:
      name: "@project.name@"
      version: "@project.version@"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/serp/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_URL}/realms/serp
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${KAFKA_GROUP_ID:spring_routing_group}
      auto-offset-reset: earliest

server:
  port: ${SERVER_PORT:9004}

app:
  kafka:
    topic:
      routing-request: ${KAFKA_ROUTING_REQUEST_TOPIC:routing_requests}
      routing-response: ${KAFKA_ROUTING_RESPONSE_TOPIC:routing_results}

security:
  role-prefix: ROLE_
  roles:
    serp_service: ${SECURITY_ROLE_SERP_SERVICE:SERP_SERVICES}
  urls:
    public-urls:
      - first: "/v2/api-docs"
        second: GET
      - first: "/v3/api-docs"
        second: GET
      - first: "/v3/api-docs/**"
        second: GET
      - first: "/swagger-resources"
        second: GET
      - first: "/swagger-resources/**"
        second: GET
      - first: "/configuration/ui"
        second: GET
      - first: "/configuration/security"
        second: GET
      - first: "/swagger-ui/**"
        second: GET
      - first: "/webjars/**"
        second: GET
      - first: "/swagger-ui.html"
        second: GET
    protected-urls:
      - url-pattern: /logistics2/api/v1/**
        roles:
          - LOGISTICS2_MANAGER
          - LOGISTICS2_SHIPPER
