CREATE TABLE kafka_dlq_messages (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    topic VARCHAR(255) NOT NULL,
                                    message_key VARCHAR(255),
                                    payload TEXT NOT NULL,
                                    error_message TEXT,
                                    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                                        CHECK (status IN ('PENDING', 'FAILED', 'PROCESSED', 'DEAD')),
                                    retry_count INTEGER NOT NULL DEFAULT 0,
                                    max_retries INTEGER NOT NULL DEFAULT 5,
                                    next_retry_at TIMESTAMP WITHOUT TIME ZONE,
                                    created_at TIMESTAMP WITHOUT TIME ZONE,
                                    updated_at TIMESTAMP WITHOUT TIME ZONE,
                                    created_by VARCHAR(255),
                                    updated_by VARCHAR(255),
                                    tenant_id BIGINT
);

CREATE INDEX idx_kafka_dlq_status_retry_time ON kafka_dlq_messages (status, next_retry_at);
CREATE INDEX idx_kafka_dlq_tenant ON kafka_dlq_messages (tenant_id);