package serp.project.school_bus_service.enums;

public enum DemoEventType {
    DEMO_CREATED,
    DEMO_STARTED,
    DEMO_PAUSED,
    DEMO_RESUMED,
    DEMO_TICK,
    DEMO_JUMPED,
    DEMO_COMPLETED,
    DEMO_STOPPED,
    DEMO_ERROR,
    DEMO_AUTO_ARRIVED_STOP,
    DEMO_AUTO_DEPARTED_STOP,
    DEMO_AUTO_ATTENDANCE,
    DEMO_AUTOMATION_SKIPPED,
    DEMO_AUTOMATION_ERROR
}
