ALTER TABLE organizations
    ADD COLUMN IF NOT EXISTS city VARCHAR(255),
    ADD COLUMN IF NOT EXISTS state VARCHAR(255),
    ADD COLUMN IF NOT EXISTS country VARCHAR(255),
    ADD COLUMN IF NOT EXISTS zip_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS tax_id VARCHAR(100),
    ADD COLUMN IF NOT EXISTS secondary_color VARCHAR(20),
    ADD COLUMN IF NOT EXISTS favicon_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS date_format VARCHAR(30),
    ADD COLUMN IF NOT EXISTS time_format VARCHAR(10),
    ADD COLUMN IF NOT EXISTS week_starts_on VARCHAR(20);
