/**
 * Author: QuanTuanHuy
 * Description: Part of Serp Project
 */

package serp.project.pmcore.domain.optimization.enums;

public enum OptimizationWarningCode {
    DEPENDENCY_CYCLE,
    EXTERNAL_DEPENDENCY,
    MISSING_ESTIMATE,
    DEFAULT_DURATION_USED,
    LOW_CONFIDENCE_DURATION,
    NO_ELIGIBLE_ASSIGNEE,
    OVER_CAPACITY,
    LATE_RISK,
    STALE_ITEM,
    PERMISSION_DENIED,
    INVALID_OVERRIDE,
    LOCKED_PLAN,
    NEUTRAL_PRIORITY_USED,
    LOW_CONFIDENCE_CAPACITY,
    MISSING_CALENDAR,
    MISSING_CROSS_PROJECT_WORKLOAD,
    NO_PROJECT_MEMBER_POOL,
    SKILL_DATA_UNAVAILABLE
}
