-- Author: Nguyen The Anh

DO $$
BEGIN
    IF to_regclass('public.checkin') IS NULL AND to_regclass('public.pickup_checkin') IS NOT NULL THEN
        ALTER TABLE pickup_checkin RENAME TO checkin;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS checkin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkin_type VARCHAR(30) NOT NULL DEFAULT 'PICKUP',
    trip_order_id BIGINT,
    order_id BIGINT NOT NULL,
    order_code VARCHAR(100),
    trip_id BIGINT,
    delivery_manifest_id BIGINT,
    delivery_manifest_order_id BIGINT,
    courier_staff_id BIGINT NOT NULL,
    checkin_time TIMESTAMP NOT NULL,
    checkin_location geography(Point, 4326) NOT NULL,
    distance_m DOUBLE PRECISION NOT NULL,
    allowed_radius_m DOUBLE PRECISION,
    photo_url TEXT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    tenant_id BIGINT
);

ALTER TABLE checkin
    ADD COLUMN IF NOT EXISTS checkin_type VARCHAR(30) NOT NULL DEFAULT 'PICKUP',
    ADD COLUMN IF NOT EXISTS order_code VARCHAR(100),
    ADD COLUMN IF NOT EXISTS delivery_manifest_id BIGINT,
    ADD COLUMN IF NOT EXISTS delivery_manifest_order_id BIGINT;

ALTER TABLE checkin
    ALTER COLUMN trip_order_id DROP NOT NULL,
    ALTER COLUMN trip_id DROP NOT NULL,
    ALTER COLUMN allowed_radius_m DROP NOT NULL;

UPDATE checkin
SET checkin_type = 'PICKUP'
WHERE checkin_type IS NULL;

DROP INDEX IF EXISTS uq_pickup_checkin_tenant_trip_order;
DROP INDEX IF EXISTS idx_pickup_checkin_tenant_order;
DROP INDEX IF EXISTS idx_pickup_checkin_tenant_trip;
DROP INDEX IF EXISTS idx_pickup_checkin_location;

CREATE UNIQUE INDEX IF NOT EXISTS uq_checkin_pickup_tenant_trip_order
    ON checkin (tenant_id, trip_order_id)
    WHERE checkin_type = 'PICKUP' AND trip_order_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_checkin_delivery_tenant_manifest_order
    ON checkin (tenant_id, delivery_manifest_order_id)
    WHERE checkin_type = 'DELIVERY' AND delivery_manifest_order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_checkin_tenant_type_order
    ON checkin (tenant_id, checkin_type, order_id);

CREATE INDEX IF NOT EXISTS idx_checkin_tenant_type_trip
    ON checkin (tenant_id, checkin_type, trip_id);

CREATE INDEX IF NOT EXISTS idx_checkin_tenant_type_manifest
    ON checkin (tenant_id, checkin_type, delivery_manifest_id);

CREATE INDEX IF NOT EXISTS idx_checkin_location
    ON checkin USING GIST (checkin_location);
