CREATE TABLE IF NOT EXISTS order_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    order_code VARCHAR(255),
    customer_order_code VARCHAR(255),
    order_status VARCHAR(255),
    description TEXT,
    post_office_id BIGINT,
    post_office_code VARCHAR(255),
    post_office_name VARCHAR(255),
    staff_id BIGINT,
    staff_code VARCHAR(255),
    staff_name VARCHAR(255),
    trip_id BIGINT,
    trip_code VARCHAR(255),
    vehicle_id BIGINT,
    vehicle_license_plate VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_label VARCHAR(500),
    event_time TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    tenant_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_order_history_order_tenant_event
    ON order_history (tenant_id, order_id, event_time DESC);

CREATE INDEX IF NOT EXISTS idx_order_history_order_code
    ON order_history (tenant_id, order_code);
