CREATE TABLE pickup_checkin (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          trip_order_id BIGINT NOT NULL,
                          order_id BIGINT NOT NULL,
                          trip_id BIGINT NOT NULL,
                          courier_staff_id BIGINT NOT NULL,
                          checkin_time TIMESTAMP NOT NULL,
                          checkin_location geography(Point, 4326) NOT NULL,
                          distance_m DOUBLE PRECISION NOT NULL,
                          allowed_radius_m DOUBLE PRECISION NOT NULL,
                          photo_url TEXT NOT NULL,
                          created_at TIMESTAMP,
                          updated_at TIMESTAMP,
                          created_by VARCHAR(255),
                          updated_by VARCHAR(255),
                          tenant_id BIGINT
);

CREATE UNIQUE INDEX uq_pickup_checkin_tenant_trip_order
    ON pickup_checkin (tenant_id, trip_order_id);

CREATE INDEX idx_pickup_checkin_tenant_order
    ON pickup_checkin (tenant_id, order_id);

CREATE INDEX idx_pickup_checkin_tenant_trip
    ON pickup_checkin (tenant_id, trip_id);

CREATE INDEX idx_pickup_checkin_location
    ON pickup_checkin USING GIST (checkin_location);
