CREATE TABLE post_offices (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              code VARCHAR(255) NOT NULL UNIQUE,
                              name VARCHAR(255) NOT NULL,
                              province_code VARCHAR(255) NOT NULL,
                              ward_code VARCHAR(255) NOT NULL,
                              address_detail TEXT NOT NULL,
                              phone_number VARCHAR(15),
                              operational_start_date DATE,
                              operational_end_date DATE,
                              working_start_time TIME,
                              working_end_time TIME,

    -- Dữ liệu địa lý (Vĩ độ, Kinh độ)
                              location GEOGRAPHY(Point, 4326),

                              service_radius_m INTEGER NOT NULL DEFAULT 5000,
                              daily_capacity INTEGER NOT NULL DEFAULT 0,
                              current_load INTEGER NOT NULL DEFAULT 0,
                              priority INTEGER NOT NULL DEFAULT 100,

    -- Enum PostOfficeStatus lưu dưới dạng String
                              status VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',

    -- Optimistic Locking
                              version BIGINT,

    -- Auditing fields
                              created_at TIMESTAMP WITHOUT TIME ZONE,
                              updated_at TIMESTAMP WITHOUT TIME ZONE,
                              created_by VARCHAR(255),
                              updated_by VARCHAR(255),

    -- Multi-tenancy
                              tenant_id BIGINT

    -- manager_id BIGINT,
                              manager_id BIGINT
);

-- Tạo Index cho location để tìm kiếm không gian nhanh hơn
CREATE INDEX idx_post_offices_location ON post_offices USING GIST (location);

-- Tạo Index cho code vì thường xuyên dùng để truy vấn
CREATE INDEX idx_post_offices_code ON post_offices (code);