-- 1. Bảng nhân sự bưu cục (Đã bỏ UNIQUE ở cột code)
CREATE TABLE post_office_staff (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   code VARCHAR(100) NOT NULL, -- Đã bỏ UNIQUE
                                   full_name VARCHAR(255) NOT NULL,
                                   phone_number VARCHAR(15),
                                   email VARCHAR(255),
                                   avatar_url TEXT,
                                   role VARCHAR(20) NOT NULL CHECK (role IN ('MANAGER', 'COURIER')),
                                   status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                                       CHECK (status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')),
                                   hire_date DATE,
                                   max_daily_stops INTEGER,
                                   max_daily_parcels INTEGER,
                                   notes TEXT,
                                   user_id BIGINT,
                                   created_at TIMESTAMP WITHOUT TIME ZONE,
                                   updated_at TIMESTAMP WITHOUT TIME ZONE,
                                   created_by VARCHAR(255),
                                   updated_by VARCHAR(255),
                                   tenant_id BIGINT
);

CREATE INDEX idx_post_office_staff_tenant ON post_office_staff (tenant_id);
CREATE INDEX idx_post_office_staff_role_status ON post_office_staff (role, status);

-- 2. Bảng phân công nhân sự (Đã bỏ các Foreign Keys)
CREATE TABLE post_office_staff_assignments (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               post_office_id BIGINT NOT NULL,
                                               staff_id BIGINT NOT NULL,
                                               assigned_from DATE NOT NULL,
                                               assigned_to DATE,
                                               shift_start_time TIME,
                                               shift_end_time TIME,
                                               is_primary BOOLEAN NOT NULL DEFAULT TRUE,
                                               notes TEXT,
                                               created_at TIMESTAMP WITHOUT TIME ZONE,
                                               updated_at TIMESTAMP WITHOUT TIME ZONE,
                                               created_by VARCHAR(255),
                                               updated_by VARCHAR(255),
                                               tenant_id BIGINT,
    -- Giữ lại các ràng buộc kiểm tra logic dữ liệu (CHECK)
                                               CONSTRAINT ck_assignment_date_range
                                                   CHECK (assigned_to IS NULL OR assigned_to >= assigned_from),
                                               CONSTRAINT ck_assignment_shift_time
                                                   CHECK ((shift_start_time IS NULL AND shift_end_time IS NULL)
                                                       OR (shift_start_time IS NOT NULL AND shift_end_time IS NOT NULL
                                                           AND shift_end_time > shift_start_time))
);

-- 3. Các Index thông thường (Không Unique)
CREATE INDEX idx_post_office_staff_assignments_office ON post_office_staff_assignments (post_office_id);
CREATE INDEX idx_post_office_staff_assignments_staff ON post_office_staff_assignments (staff_id);
CREATE INDEX idx_post_office_staff_assignments_tenant ON post_office_staff_assignments (tenant_id);

-- (Đã loại bỏ Unique Index uq_staff_single_active_assignment tại đây)