CREATE TABLE trips (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     trip_code VARCHAR(100) NOT NULL,
                     post_office_id BIGINT NOT NULL,
                     courier_staff_id BIGINT NOT NULL,
                     vehicle_id BIGINT,
                     shift VARCHAR(20) NOT NULL
                         CHECK (shift IN ('MORNING', 'AFTERNOON', 'EVENING')),
                     trip_date DATE NOT NULL,
                     planned_start_time TIMESTAMP,
                     planned_end_time TIMESTAMP,
                     total_orders INT NOT NULL DEFAULT 0,
                     total_distance_km DOUBLE PRECISION NOT NULL DEFAULT 0,
                     total_travel_minutes BIGINT NOT NULL DEFAULT 0,
                     status VARCHAR(20) NOT NULL DEFAULT 'PLANNED'
                         CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
                     created_at TIMESTAMP,
                     updated_at TIMESTAMP,
                     created_by VARCHAR(255),
                     updated_by VARCHAR(255),
                     tenant_id BIGINT
);

CREATE UNIQUE INDEX uq_trips_tenant_trip_code
    ON trips (tenant_id, trip_code);

CREATE INDEX idx_trips_scope
    ON trips (tenant_id, post_office_id, courier_staff_id, trip_date, shift, status);

CREATE TABLE trip_order (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          trip_id BIGINT NOT NULL,
                          order_id BIGINT NOT NULL,
                          sequence_no INT NOT NULL,
                          distance_from_previous_km DOUBLE PRECISION,
                          travel_minutes BIGINT,
                          planned_arrival_time TIMESTAMP,
                          planned_start_service_time TIMESTAMP,
                          planned_departure_time TIMESTAMP,
                          lateness_minutes BIGINT,
                          created_at TIMESTAMP,
                          updated_at TIMESTAMP,
                          created_by VARCHAR(255),
                          updated_by VARCHAR(255),
                          tenant_id BIGINT,
                          CONSTRAINT fk_trip_order_trip
                              FOREIGN KEY (trip_id)
                                  REFERENCES trips(id)
                                  ON DELETE CASCADE,
                          CONSTRAINT uq_trip_order_trip_order
                              UNIQUE (trip_id, order_id)
);

CREATE INDEX idx_trip_order_trip_sequence
    ON trip_order (trip_id, sequence_no);

CREATE INDEX idx_trip_order_order
    ON trip_order (order_id);

CREATE INDEX idx_trip_order_tenant
    ON trip_order (tenant_id);
