CREATE TABLE vehicles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          license_plate VARCHAR(50) NOT NULL,
                          max_weight DOUBLE PRECISION,
                          max_volume DOUBLE PRECISION,
                          vehicle_type VARCHAR(20) NOT NULL DEFAULT 'BIKE',
                          image_url TEXT,
                          post_office_id BIGINT,
                          post_office_staff_id BIGINT,
                          status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                          created_at TIMESTAMP WITHOUT TIME ZONE,
                          updated_at TIMESTAMP WITHOUT TIME ZONE,
                          created_by VARCHAR(255),
                          updated_by VARCHAR(255),
                          tenant_id BIGINT
);

-- Các Index
CREATE INDEX idx_vehicles_tenant ON vehicles (tenant_id);
CREATE INDEX idx_vehicles_post_office ON vehicles (post_office_id);
CREATE INDEX idx_vehicles_post_office_staff ON vehicles (post_office_staff_id);

CREATE UNIQUE INDEX uq_vehicles_tenant_license_plate
    ON vehicles (tenant_id, lower(trim(license_plate)));