CREATE TABLE vehicles (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         license_plate VARCHAR(50) NOT NULL,
                         max_weight DOUBLE PRECISION,
                         max_volume DOUBLE PRECISION,
                         post_office_id BIGINT,
                         post_office_staff_id BIGINT,
                         status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                             CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'IN_USE', 'FULL')),
                         created_at TIMESTAMP WITHOUT TIME ZONE,
                         updated_at TIMESTAMP WITHOUT TIME ZONE,
                         created_by VARCHAR(255),
                         updated_by VARCHAR(255),
                         tenant_id BIGINT,
                         CONSTRAINT fk_vehicles_post_office
                             FOREIGN KEY (post_office_id)
                                 REFERENCES post_offices(id),
                         CONSTRAINT fk_vehicles_post_office_staff
                             FOREIGN KEY (post_office_staff_id)
                                 REFERENCES post_office_staff(id)
);

CREATE INDEX idx_vehicles_tenant ON vehicles (tenant_id);
CREATE INDEX idx_vehicles_post_office ON vehicles (post_office_id);
CREATE INDEX idx_vehicles_post_office_staff ON vehicles (post_office_staff_id);

CREATE UNIQUE INDEX uq_vehicles_tenant_license_plate
    ON vehicles (tenant_id, lower(trim(license_plate)));
