CREATE TABLE hub_staffs (
    -- Các trường từ class HubStaff
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            code VARCHAR(255),
                            full_name VARCHAR(255),
                            phone_number VARCHAR(255),
                            email VARCHAR(255),
                            role VARCHAR(255),
                            status VARCHAR(255),
                            hire_date DATE,
                            user_id BIGINT,
                            avatar_url VARCHAR(255),
                            note TEXT,

    -- Các trường kế thừa từ AbstractAudit
                            created_at TIMESTAMP WITHOUT TIME ZONE,
                            updated_at TIMESTAMP WITHOUT TIME ZONE,
                            created_by VARCHAR(255),
                            updated_by VARCHAR(255),
                            tenant_id BIGINT
);

CREATE INDEX idx_hub_staffs_user_id ON hub_staffs(user_id);
CREATE INDEX idx_hub_staffs_tenant_id ON hub_staffs(tenant_id);
CREATE UNIQUE INDEX idx_hub_staffs_code ON hub_staffs(code);