-- Author: Nguyen The Anh

CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(100),
    aggregate_id VARCHAR(255),
    event_type VARCHAR(150) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    message_key VARCHAR(255),
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'FAILED', 'PUBLISHED', 'DEAD')),
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 5,
    next_retry_at TIMESTAMP WITHOUT TIME ZONE,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    error_message TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    tenant_id BIGINT
);

CREATE INDEX idx_outbox_events_status_retry_time ON outbox_events (status, next_retry_at);
CREATE INDEX idx_outbox_events_tenant ON outbox_events (tenant_id);
CREATE INDEX idx_outbox_events_topic ON outbox_events (topic);
