-- Author: Nguyen The Anh
-- Description: Part of Serp Project - Tenant bag capacity defaults

CREATE TABLE IF NOT EXISTS bag_capacity_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_weight DOUBLE PRECISION NOT NULL DEFAULT 50.0,
    max_volume DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    max_orders INT NOT NULL DEFAULT 30,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    tenant_id BIGINT NOT NULL,
    CONSTRAINT uq_bag_capacity_settings_tenant UNIQUE (tenant_id)
);

INSERT INTO bag_capacity_settings (
    max_weight,
    max_volume,
    max_orders,
    tenant_id,
    created_at,
    updated_at,
    created_by,
    updated_by
)
VALUES (
    50.0,
    0.5,
    30,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    'system',
    'system'
)
ON CONFLICT (tenant_id) DO NOTHING;
