CREATE TABLE hub_staff_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id BIGINT NOT NULL,
    staff_id BIGINT NOT NULL,
    assigned_from DATE NOT NULL,
    assigned_to DATE,
    is_primary BOOLEAN DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    tenant_id BIGINT,
    CONSTRAINT fk_hub_staff_assignments_hub FOREIGN KEY (hub_id) REFERENCES hubs (id),
    CONSTRAINT fk_hub_staff_assignments_staff FOREIGN KEY (staff_id) REFERENCES hub_staffs (id)
);

CREATE INDEX idx_hub_staff_assignments_hub ON hub_staff_assignments (hub_id);
CREATE INDEX idx_hub_staff_assignments_staff ON hub_staff_assignments (staff_id);
CREATE INDEX idx_hub_staff_assignments_tenant ON hub_staff_assignments (tenant_id);

CREATE UNIQUE INDEX uq_hub_staff_active_assignment
    ON hub_staff_assignments (tenant_id, staff_id)
    WHERE assigned_to IS NULL;
